version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invest-trainer-app
    volumes:
      - ./web:/usr/src/app/web
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=your_secret_key_here
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
      - ON_RENDER=False
      - DATABASE_URL=postgresql://neondb_owner:npg_gXJC4cKrlBO1@ep-frosty-waterfall-a4xr3fax.us-east-1.aws.neon.tech/neondb?sslmode=require
      - AWS_STORAGE_BUCKET_NAME=risklab-media
      - AWS_ACCESS_KEY_ID=YCAJEgK6EfDF9PpNz4s_OyaPM
      - AWS_SECRET_ACCESS_KEY=YCMybhCIN5qI7zvr0TMp1qxa9ds7toBTQ0nZo272
    restart: unless-stopped

volumes:
  media_volume: