# Generated by Django 5.2.7 on 2026-04-01 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "game_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID игры",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название игры"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Ожидание игроков"),
                            ("active", "Активна"),
                            ("finished", "Завершена"),
                        ],
                        default="waiting",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "start_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000000,
                        max_digits=12,
                        verbose_name="Стартовый капитал",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Игра",
                "verbose_name_plural": "Игры",
            },
        ),
        migrations.CreateModel(
            name="GameHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Количество"),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Средняя цена покупки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция в игре",
                "verbose_name_plural": "Позиции в игре",
            },
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_name",
                    models.CharField(
                        max_length=100, verbose_name="Имя игрока"
                    ),
                ),
                (
                    "is_guest",
                    models.BooleanField(default=True, verbose_name="Гость"),
                ),
                (
                    "cash",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Наличные",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Текущая стоимость",
                    ),
                ),
                (
                    "final_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Итоговая стоимость",
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="Коэффициент Шарпа",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Прибыль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник игры",
                "verbose_name_plural": "Участники игр",
            },
        ),
        migrations.CreateModel(
            name="GameTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("buy", "Покупка"), ("sell", "Продажа")],
                        max_length=4,
                        verbose_name="Тип операции",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Цена сделки",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Сделка в игре",
                "verbose_name_plural": "Сделки в игре",
                "ordering": ["-created_at"],
            },
        ),
    ]
