# Generated by Django 5.2.7 on 2026-03-31 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0001_initial"),
        ("stocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_games",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="gameholding",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stocks.stock",
                verbose_name="Акция",
            ),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="game.game",
                verbose_name="Игра",
            ),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="gameholding",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holdings",
                to="game.gameplayer",
                verbose_name="Игрок",
            ),
        ),
        migrations.AddField(
            model_name="gametransaction",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="game.gameplayer",
                verbose_name="Игрок",
            ),
        ),
        migrations.AddField(
            model_name="gametransaction",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stocks.stock",
                verbose_name="Акция",
            ),
        ),
    ]
