# Generated by Django 5.2.7 on 2026-04-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="rank",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Место"
            ),
        ),
    ]
