# Generated by Django 5.2.7 on 2026-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_gameplayer_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="game_qr_codes/",
                verbose_name="QR-код",
            ),
        ),
    ]
