# Generated by Django 5.2.7 on 2026-04-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_game_qr_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="qr_code",
        ),
    ]
