# Generated by Django 5.2.7 on 2026-03-31 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000000,
                        max_digits=12,
                        verbose_name="Наличные",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000000,
                        max_digits=12,
                        verbose_name="Общая стоимость",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Личный портфель",
                "verbose_name_plural": "Личные портфели",
            },
        ),
        migrations.CreateModel(
            name="PersonalTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("buy", "Покупка"), ("sell", "Продажа")],
                        max_length=4,
                        verbose_name="Тип операции",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Цена сделки",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Сделка",
                "verbose_name_plural": "Сделки",
            },
        ),
        migrations.CreateModel(
            name="PersonalHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Количество"),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Средняя цена покупки",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stock",
                        verbose_name="Акция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция",
                "verbose_name_plural": "Позиции",
            },
        ),
    ]
