# Generated by Django 5.2.7 on 2026-04-02 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaltransaction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
