# Generated by Django 5.2.7 on 2026-03-31 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
        ("trading", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="personalportfolio",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_portfolio",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="personalholding",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holdings",
                to="trading.personalportfolio",
                verbose_name="Портфель",
            ),
        ),
        migrations.AddField(
            model_name="personaltransaction",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="trading.personalportfolio",
                verbose_name="Портфель",
            ),
        ),
        migrations.AddField(
            model_name="personaltransaction",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stocks.stock",
                verbose_name="Акция",
            ),
        ),
    ]
