# Generated by Django 5.2.7 on 2026-03-31 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "impacts",
                    models.JSONField(verbose_name="Коэффициенты изменения"),
                ),
            ],
            options={
                "verbose_name": "Сценарий",
                "verbose_name_plural": "Сценарии",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Тикер"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название компании"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Описание компании"
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("oil_gas", "Нефтегаз"),
                            ("retail", "Сеть магазинов"),
                            ("bank", "Банк"),
                            ("metallurgy", "Металлургия"),
                            ("transport", "Транспорт"),
                            ("it", "IT сектор"),
                        ],
                        max_length=50,
                        verbose_name="Сектор экономики",
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Текущая дивидендная доходность",
                        max_digits=5,
                        verbose_name="Дивидендная доходность (%)",
                    ),
                ),
                (
                    "dividend_history",
                    models.TextField(
                        blank=True,
                        help_text='Например: "Cтабильно платит дивиденды с 2010 года"',
                        verbose_name="Дивидендная история",
                    ),
                ),
                (
                    "volatility",
                    models.CharField(
                        choices=[
                            ("low", "Низкая"),
                            ("medium", "Средняя"),
                            ("high", "Высокая"),
                        ],
                        max_length=10,
                        verbose_name="Волатильность",
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Текущая стоимость акции",
                        max_digits=12,
                        verbose_name="Последняя цена (LAST)",
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Для сравнения с началом дня",
                        max_digits=12,
                        verbose_name="Цена открытия (OPEN)",
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Для оценки волатильности",
                        max_digits=12,
                        verbose_name="Максимум за день (HIGH)",
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Для оценки волатильности",
                        max_digits=12,
                        verbose_name="Минимум за день (LOW)",
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        default=0,
                        help_text="Ликвидность акции",
                        verbose_name="Объем в штуках (VOLUME)",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Денежный объем торгов",
                        max_digits=20,
                        verbose_name="Оборот в рублях (VALUE)",
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Прибыль/убыток за день",
                        max_digits=12,
                        verbose_name="Изменение в рублях (CHANGE)",
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Относительное изменение",
                        max_digits=8,
                        verbose_name="Изменение в процентах (CHANGEPERCENT)",
                    ),
                ),
                (
                    "last_price_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление цены"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
            },
        ),
        migrations.CreateModel(
            name="StockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Цена открытия",
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Максимум",
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Минимум"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Цена закрытия",
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        default=0, verbose_name="Объем торгов"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="stocks.stock",
                        verbose_name="Акция",
                    ),
                ),
            ],
            options={
                "verbose_name": "История цен",
                "verbose_name_plural": "Истории цен",
            },
        ),
    ]
