# Generated by Django 5.2.7 on 2026-04-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('ticker',), 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
