# Generated by Django 5.2.7 on 2026-04-02 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockhistory",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время"
            ),
        ),
    ]
