# Generated by Django 5.2.7 on 2026-03-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users_images/",
                verbose_name="Аватар",
            ),
        ),
    ]
